services:
  video-queue:
    image: rabbitmq:3-management
    container_name: video-queue
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - public_net
      - internal_net
  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - public_net
      - internal_net
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=retube
    ports:
      - "5432:5432"
    volumes:
      - ./file-storage/db:/var/lib/postgresql/data
    networks:
      - public_net
      - internal_net
  uploader-v4:
    depends_on:
      - db
      - cache
      - video-queue
    container_name: uploader-v4
    build:
      context: ./uploader-v4
    networks:
      - internal_net
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://db:5432/retube
      - FFLOW_CACHE_HOST=cache
      - AMQP_CONNECTION_STRING=amqp://video-queue

networks:
  public_net:
    driver: bridge
  internal_net:
    driver: bridge
    internal: true
