x-fflow-common: &fflow_common
  build:
    context: fflow
    dockerfile: Dockerfile
  volumes:
    - ./file-storage/fflow-data:/data
  expose:
    - "5050"
  environment: &fflow_env
    PORT: 5050
    HOST: localhost:5050
    DATA_FOLDER: /data
    # FFMPEG настройки не указываем, так как они уже предусмотрены по дефолту
    FTP_SERVER_HOST: holder-balancer
    FTP_SERVER_PORT: 21
  networks:
    - internal_net
services:
  holder:
    build:
      context: holder
      dockerfile: ../service.Dockerfile
    expose:
      - "4000"
      - "4001"
      - "4002"
      - "4003"
      - "4004"
      - "21"
      - "4050"
    environment:
      - ROOT_PATH=/data
      - DISTRIBUTION_PORT=4050
      - PLAYER_ORIGIN=http://localhost:3000
      - FTP_URL=ftp://0.0.0.0:21
    volumes:
      - ./file-storage/holder:/data
    networks:
      - internal_net
  holder-balancer:
    depends_on:
      - holder
    image: nginx:latest
    container_name: holder-balancer
    # Раздача статики холдера
    ports:
      - "4050:4050"
    volumes:
      - ./holder.nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "4000"
      - "4001"
      - "4002"
      - "4003"
      - "4004"
      - "21"
    networks:
      - internal_net
      - public_net
  fflow-1:
    <<: *fflow_common
    container_name: fflow-1
    environment:
      <<: *fflow_env
      GLOBAL_PREFIX: /r1
  fflow-2:
    <<: *fflow_common
    container_name: fflow-2
    environment:
      <<: *fflow_env
      GLOBAL_PREFIX: /r2
  fflow-3:
    <<: *fflow_common
    container_name: fflow-3
    environment:
      <<: *fflow_env
      GLOBAL_PREFIX: /r3
  fflow-balancer:
    depends_on:
      - fflow-1
      - fflow-2
      - fflow-3
    image: nginx:latest
    container_name: fflow-balancer
    ports:
      - "5050:5050"
    volumes:
      - ./fflow.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./file-storage/fflow/log:/var/log/nginx
    networks:
      - internal_net
      - public_net
  video-queue:
    image: rabbitmq:3-management
    container_name: video-queue
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=retube
    ports:
      - "5432:5432"
    volumes:
      - ./file-storage/db:/var/lib/postgresql/data

networks:
  public_net:
    driver: bridge
  internal_net:
    driver: bridge
    internal: true
